#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config external_bar off:45:0
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                float
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.6

yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          6
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20 
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

# mission-control desktop labels
yabai -m space 1 --label term
yabai -m space 2 --label web
yabai -m space 3 --label code
yabai -m space 4 --label web
yabai -m space 5 --label notes
yabai -m space 6 --label media
yabai -m space 7 --label social


# yabai -m config --space 5 layout             float
# yabai -m rule --add app=Telegram space=5 grid=1:3:2:0:1:1
yabai -m rule --add app=Telegram space=social
yabai -m rule --add app=Spotify space=media
yabai -m rule --add app=Slack space=social
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

echo "yabai configuration loaded.."
