#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config external_bar                 all:34:0
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
# yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.6
yabai -m config window_animation_frame_rate  120

# yabai -m config window_border                off
# yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xff775759
# yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6

# mission-control desktop labels
yabai -m space 1 --label term
yabai -m space 2 --label web
yabai -m space 3 --label code
yabai -m space 4 --label web2
yabai -m space 5 --label notes
yabai -m space 6 --label media
yabai -m space 7 --label social


# yabai -m config --space 5 layout             float
# yabai -m rule --add app=Telegram space=5 grid=1:3:2:0:1:1
# yabai -m rule --add app=Telegram space=social
# yabai -m rule --add app=Spotify space=social
# yabai -m rule --add app="^Spotify$" scratchpad=spotify grid=11:11:1:1:9:9
# yabai -m rule --add app=Slack space=social

yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app=krisp manage=off sticky=on
yabai -m rule --add app="Drata Agent" manage=off sticky=on
yabai -m rule --add app="ProtonVPN" manage=off sticky=on
yabai -m rule --add app="^qemu-system-aarch64$" manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
